---
kind: pipeline
type: docker
name: Default

trigger:
  event:
    - push

steps:

  - name: generate-tags
    image: quay.io/natlibfi/drone-gen-tags

  - name: audit
    image: node:12
    commands:
      - npm audit --package-lock-only --audit-level=moderate --production

  - name: install
    image: node:12
    commands:
      - npm ci
    environment:
      NPM_CONFIG_IGNORE_SCRIPTS: true

  - name: test
    image: node:12
    commands:
      - npm test

  - name: check-coverage
    image: node:12
    commands:
      - npm run check-coverage

  - name: build
    image: node:12
    commands:
      - npm run build

  - name: static-security-scan
    image: quay.io/natlibfi/njsscan
    commands:
      - njsscan dist

  - name: docker
    image: plugins/docker
    settings:
      repo: quay.io/natlibfi/
      registry: quay.io
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
---
kind: pipeline
type: docker
name: Update dependencies

trigger:
  event:
    - custom
  branch:
    - master

steps:

  - name: publish
    image: quay.io/natlibfi/drone-npm-git-publish
    settings:
      git_user_name: natlibfi-melinda-automation
      git_user_email: 65649125+natlibfi-melinda-automation@users.noreply.github.com
      git_ssh_key:
        from_secret: ssh_key
      git_gpg_key:
        from_secret: gpg_key
---
kind: secret
name: docker_username
data:
---
kind: secret
name: docker_password
data:
---
kind: secret
name: ssh_key
data: OLPegzrddhh/K+9s7tjpfU4FkUgarkZnfV/nbF8aSX8ims07+JrpntyWHUyTGDfWGFkfMkrqws2fbP9nbVjwikWhDFYRvPcX3obr/Q4Z2ZCS3DhnNP87qgjPokAP4drSSbWV3IydWo9I4/uHPCUc9Psel45rwyVsm/HgDcRaZPux9kOhIkLES4JEitjORC6mGGuD381VxjP0zRCInggwWRfgvNIVGvxVaGiZK86avMoWqIG+98oJv1XatUDxfCEmyJPZAwiIYx0AL8/lvFizn0Vf3N3VXXHZ1t9BIdASuBKd11HGHwSxrSSN8620vRHhD42/Vyw56nrPOk6VUGTJyuhGbAFIDPSW1VfNILG3mvbJCEiAGECEIQreSDGULZPQ2MAEqbs6ZBdqYBSWasLnxiMvTIxUL2FMcKkj9RLmKuURu1P3BXTzaK5vs1CaaCJvhFw46IG0xuOmDcSViXjjjRijgQ8ZSy9dndlJKMyowtyrPXLZiM/NEnhVduvgmsj5Qfy35XhB47Ko1P7w5J8L5o/tvenZJWvxT1J05cVmwnqFnurHKPcXYedRYrMIammJI9MlVrnZXFXiCl8AX2q7GVz0riIjgd/Xi1oG8DvJLPJDFyoCBEx5WI+6WJGJWRmpjLRaOzHX5xeDj70w9wmf4YxY6C/yMMTtlL5gJWl5cPgkz0kaTD6dQOYmHqMFQ042DjL0CKWHRn7wTfXLbcYC5N4Uwa/YMadKuVQZ+TmSwgK17XooJiMw3rEV7HHwdXL2sEc/4bEhAskTCUjAoQ//O/ZWWKA8sLh6IzFOzLiUAizs5HWTB04ZDWDRwMEoapur80zENVMKrZU4EeSXKoRTz+RqFRdmbbChhhaug+7RYHCoUCQJ+AZDHTsiWteUuICc7pUDdJmHsRLsZOqsA751clwiyAz31LOr4n0RTwJGxBUrO0TM9oqyA4b7S7m0UJX+9LNTImteDXxIrZlQpArPily4V4Zx8mlo03fjBsoSEL3Up0Ge1Z6uWYyYsbfIP9W4itbEdqRIKrfYOnm8cytQpfOyz6zygmzTq9aW1bw8NyEYW3F/N+Kbpze/bFVVuonU7X7+zjj93w3NlIn6voxPdHnt7hBEAnZKvvBbzucs+NRO9IhA2AzMxCW85Ij0PfJ1BUEGmunLFpHLQ/OeKlUwHOeFnB7R42YdwDxYEniB8qSdk9V0hLbQHl9qk9b7Lc8YkI7bw616TWcMtTT+cLOx2qQM+668+vhvGtAky/sX8uaf3DOg1N5U6mR73O5nIS14yxndQ9fcbeGRLjbiC4XaAufI78UYuTRnMUOTxcj9h1//6bKX0L2zTlqaneWY+8TMQQRHJZhWp84jhSSHTV8z5NlD75dVL1PpBSX9Hpx/OsDYrXM3W17Q7VSVOoP9NIik7pMOLd0kBGKG+PLTtlocNk17kS7Ej9WpOVMpsjpXaouvNTekIwbAzbHUvSAv16c09Raf7HZyi5hwIGduiCE/fL01pp2dxn405EMdjt1PhNXL8vCEGT5TQcjeVs1+SJjrvVi5w4yr/FBYRlOe8WqxUm75e+bVKEIVWqNEY70c1oXxTrM0u39W8LxtPFoK+wG1jeQEXcPSmVS8vrS+UOzQSgw1Exr0Z5eU2h1lEZxhL+OUqkZFreGN0M/xORmzO0vo/993xoN7sFAWzfd6qhw+INxIbeQB1Hwp3cfFxDhCNyAsHYbIWlbHM7G+6p/A8qwOrzOZ8fYMrxfriQA0lef6IVEZmarV40jzyIfvSbxKzuXT994WRPhUhyWypIASiKfS7Un+v+QC1UipfFBXhHA5lp/bnLIoVLPVv7Mu+dZQ7r946ZO5S4v3JYcstzCDLSzLSwmEHThVd9ACE6koY/jKJz29gCQnS3ILftlXvXyOEdot96uP0Hk1AF5odQWOwl1cxl1Uv0+kgjjsGic74b34RZNbCV47JttHgE2b+9lVhoaEld9hLNv+++GvD3+Mwoh4ii94j24HzBLEa64V7mlfdz5ILq7MES4dtXVsayQgS09PUNdyk+2wEWlDcarlLntFV3Ecx3ySpmZvNoWWy8/4OtLchG2WzSxrxdlDWwQb1J5D9OX+F/SJoOjAAShk1klO4KEmNAmlVmfDSbheNNk7zQQBKY+9Qv6sDEBiSLeQwJNQZSlAzP6P+rfk2hMSC7qpHYFuhyKl1ajlCf6LakAW140VMolX5TlGx6QgLp8WMGmRZfyeyuHjuQnttXYHRn1xk+XVh9HiTwdIiDiX7PfUNnL94/gwdZaC6pkzk9CltNFKdHAAcSa7mrwMHVBLh7UfKhU1LJzB+pmx097BSAiJrMaVAlhXBD9s35jJ3BAeN9+xRaQdlNty/ssiBACXKzW+mcrsZZLwoUA0GhWR+g24cLX+r/FLBrPyhyUFhgW/Zdgnzz0K/Vdtsvf7Sga2RJPyfTFImk32mxP3TV00FUFeVYwOW24R75LG4xdaW04GexJklBZgJcoSYJf1S6+1CkWF9AhrXEHyvmbv3hOCZUeOZitKbYFg0pGzV2TUZcAwGeBM5YkUnhYsfzkuvUKadxGKDbwuf2gIW81ouvxhj3gXqp/L6nUzYYMcndjLHoiFEk8iEKmYGB2/Wv0twZxPMXjVWjHuT+XdaeBhNqssRBWmtmki6VeZNDlIUALgD/ezTXobpQH48lmOx8pC9H8YNW4Qa2HJel7H3hpvcANk2sZC/+H3T6H2nJVLPdruT2O66JxS5maCTgA5v2OgFTqlCu7kGhpPOZ1O8G4KfY8I66AyeoE7v1drmPG8MINaIKfrAywCeINHrK9Wev4d6AvnOIfHBVIfgc5+rjS3kyBoVQ+PwVKKGEmEkaKObchjZfb7Ja/CbGy4utV1NV/6HIsdq9mD+afL7/BSEhpRv4HIHratW+JnWpu37SG67rYw9u6+tXlntaPsbSNxlytbk2BcV6bZEmbe3r3vPAlt55SuYUTgECyw7zCVvr4dRg8ZFiXGnrUpTg1NAq5GOWXP7OWijkBLj3mGl0VZKXGedBDX
---
kind: secret
name: gpg_key
data: IgwRUcyhGVZTZvR3ZJ7prq7L5Mn7XO47N58HYZOO41KW9bqykgxXZ+NhfYL+UNNm4EfR2Y6L0qkt4Ptw+yh80xyfZOOFQk9rG4LXUHqFgEI2uskpk5nuxhTGfeMV339xZ/Z4YUjkvuZ/H6vbg75g7NArIk0SXuUbhyVoM6iNY4G3uRk9gUd37no5ui6cjYgQ+H9nsmW+oLSriKzQbi5cPOOuUdQ7Wi8xSMmL1vxvgcgaIsHeuVGf8zJiD7t4tLaAEVZNZ8pbmRWkW66DrpdftRO3ffB31tD8/+1aKjqwveLNMGd6/VQTOIoQREhfa5mNox7khN6rqyGkgPALYYKOctK0tBIG7X37s9olUv0QRB2w/LkATQOvsbTtxxcK5Fs87YF7FmsqKXPcvobaXIiIFvMHaO/Ki0SClJlzgCj1SajIDaxcBM9soibLF+WdRa02EFDo3mRMv/oRpyqlFkF1eHLDN1PYpCg5wRYAVIIY4thcorQvMutrnElnr2kPmFuoqdGYEhmtQKAMPoca/+FEn3T9lc7X271R+8raiuNCt2nwnH9mWxCzLs4eyXHcCYVvQuzj3JDwgyGPsQ5nRCcZTtf8U93FtnPazoadMeUHWG7SB/GMB+kxHqWM/zU0r2HD05j3V0kDhJt/FnvRp8C82YArd9MH13cNT6Q9nymBOzScCB72hpXUTF9irJ1K4qUdWr4UBpt9Des4ie16TovmOXZSOYaMf1MHzUULEb95jczuD/NRFVj6+aPMZvtlxppn82E2Y+XFfsXocNCE7mAgOSYs5wvgEYgu4pmcRgjhuyhVaUaR6WmORriZ70KwiO/hOcYuMRtxsIFHMade5l3HP1zgRYj+WIAgfZs6TtOFoIFZK5Y08p3k5mMB+G5bCo4PgEwmPhSX/qp68KypLFDojtKHkkiQEZ2IoUUIFbfxFpfdB/mPPn8DmtrIzByoWGSybDs6WYphcyFtRnNg33PNaywZIc+dOWH9G0ajRDjGTs70aGsakM3CTzQoRzMYnLujyf3eOMNkybBd+Juk1nnmQ+qzAmwjjBR43F524P4rSLbuCuQo6mEurGM4PXbYtopvH5ogX0QiWYaTunGoIszKlS6j+XNcNfoedGxAuEDBMVMYnHbnXkuPXUGAWxZ8+ePRcBsXRRyTSSwnC54NTsnEX47KNGjXWs1Apm/xmNQGazp3CF7FDakPdqBn0fjv5R1GPFBp7gZLiCFPjq37VeH8QebV16kcLcim6tr6LAZ8eMG1Cc5oV6E+MvLDDM2mn9lnWb/hlIwjU++DfKGuIWzL/dG6XCxYlmu+c+U1ASO91tM8oON9U8sc9rs3+dZl0zq3+l3MYXtBeEW09EMD2hgrqN3EH/9wRgrQ3Orb9Rdbx8mrM2pYTmbfysK3Rv645ba5tPO/uKu5KfsyigE4ASFtaAUqskSWAWODEeonIaw+9k5etD9z88vmhxNvAuQSaQfEMCMfLtPw5UyMcNxxyaJECWuGzXUc5RPm4tytPYRlg+FEFH2junL5ZiTaHXoU4DD0d74bW4THBT+ZpeUVqr1HuWj0tpI0cY6xq7tyKhION0GanS4HMwBrBom4xqPCS+G1nMpQ4M0qPiybIJE5RqeZsFOWIN/6rL0iKikYKXcSoMTNHO9Ishrz0EQc/Xcwmz5mCrmC6dkbF9wfB+An+/S5otdAEgFn08VBxYcih1dHyrNkVDJAblMlLOS/rztZxfEVySskkQlfksB1JLHFtJpF98WwOFUYbQbBdYHPPUDQygivwP/vfk5gOuInEF+BosZzyi5V8skZGB3MQhOBsxIroCrOEnF4BBppShOVL00Qb1NPXfTIqAG+I4mt+pOVVu5cCFiGoOm1n1e6wVviLZEtyRYKRQub9siI4u2Wz1xiMlFwinX/l7NzsUsad77IXZHwo7azih09aipTM0kHJtY9snFMv7w45PKbyizMf/JzUQP/3PLWRBSB/hUZbOX2x3Zl9JxdZcukdKOH7CpQkYAjLVlcovbK952VeAlECfAooT0VQH3r3VCgiE1Y9afBmaBwhfvnHsgQ8ka0zpNtrhSG1/XkXFKJkw8ZBOHCvi3kwW5Hwk2EMCYJZkbo21AkvWhJSkY1xPGcybIDHvupWi7ISh5NTQ/YJ7TjKKjxeKq7h1oCh8ulf5b16XAEueXyQTA9Ulq1js9BXKI1FEZqBzqc4Q93Oy6QcWQ+lDmoT1EwocH2kBj4msDny0Uqd4fz1RjtE5hRQXsYeK+Uq4jhiaBvTwRxCGsG+eirMmbbvIWwh4kLXZTTCW3J3WussnzRsxLFmO75xeiBj2jiEAM2T8EAewTloep55p8QdAEnAjqg8IbthCUOqiDnHQN0VXy3pK4iGYs5sgpkX56LBrIc7DWiXtMVJGIJIsaL40UOR+lAstLDAgTsccth0spBI0nHOFKHkMsVKk9GOf036zWgVVAvjDaEuG1QaVxBthY5CEhhL3geeX8U8Xai9bZoWk1CiQkXA1AQMRA+JlQciDSoPeNCTTmw2pswtsP/15Yfw64eDhuZYcXTEtXbum+AY+jqz7yIKx1jpbTaX32fLsXY7F/XVHWeGcmij9rcpvbnLUFv7U5zPbxmWbn3/U9c3tcRNxawY/fHRwwYQdQkIHKFx4zfVHQmdMWGYKbRGXMRIEExbjNLF1BczVGgLbZQTbfuMHmb0zdSTtgC3PsSjHJ2BbvBfmdAMPFkR3HPiv5jdTBKb8SPTOAZpLDxX6zLXIqaDUIp5LjrFqWFPUvDMQHDBi2Z9Ru75mCjYjmWQUz5YeP/hJSAmxZVSylnOi2NtE9C1yIKxS5I4OU/X8wpfiI8TeGeOlIVhD8abD0O2FbNqgFfU8xLLmfM57nVvVgeEnhpXEmHxh7P6F6kJhKy7dw/wHX4Hd6Nw6+hNvmqs5F9YZk48pFBM3mYYxvEg4kJzqCJworyrtbIq1b9j/SuFHuAWiDHsnntUd13jBcf96PWW5vL8OrJOVcbWdzG7VnhV3OPUjyXkBiNfeuwdlubTNfAX0WGDoB6cmxuhRMKep2P50hsHkFVKuJuFn1eJzHueLnMrFdzKDDprChZJGh+Yq54BLZS0R65rI7E1AH+Mcj878Ifb8K/7bbZrbEXED7uf8ZU2sPI203ej3jC6DiIwMNJFBbSTFHx5mLZnklQihsArBnNNFllRs92caUzYAHjbM6PHgBEsTlOYTFdFhlrHa4JpkzM+wTM+ROkipivVoWrCDqkaVd2IS2FwQy5nYUjoqHrQ5RCEdlcaFJq9+wd66pi95+knTyQ2a7eZSwEUEtXw8HYhuvsqcvpDCmpo/+HXZmd+uPRiSjOcgKwSkWhGJRalEXnrxbipcG6i9D+ZhZLlI7Wq/03iKnEDm2fmxxhDYsaeeVOfBefEL8xWIP3yQki6gsyIVhmaGXxHvDoB7lmRGRpW6vDbI8tYGwoxUmPQRU0sMlEk1xjBBd9bgCNeLexMjO4Of8VBmQiUFjKbS4/EiwmUe37OJ80kqOaAJ45EbE1QOVk4ubYgGX29NK/deBsWXLE+zdcLT7v4tXkd2eNtweeYEFGgOr3oxr5pQzJygQUicCuLVrIFxFE42cten1Lw7+3ZxDg3B8Do157mCOR/xk7PkAjlNBrYssCC1t3vcKgT/9admyjGjis40zYMVETamf5Iv6Vo2alvoCwbOXWY0FSLlITKJF4Ds2rp/hVFRFudWZruPnqljCs2cA1HpNBifgaIJdv0XSGlyYAFrEWcMLNQnMb4CWUBZmts19MSai2S7QSa888avdf8wKRvFgynbs3q604+fpL6KdzqqnL/+xjdgGo2ssO9hwy94T+DhI4NvUDdVk11NgZpoPopp34EoHNEfg/rmTtUGlCBdOMn0gsQyTtMKUSoJrAd5aQUe5JTJ8mXfYWpH3xH8/aknLmGZWVxAvdaAoWLzd5i6+HL8RQzhL9XlxqOiiS6SwteJ0fw1XWLsr5mYJiASXvpCb6S+t7RDyxmtCYQV7CwNEq1wJtTAS9uF8F8F1rHpJu5L8URHyq0DBFQFxoyYCkLEIUModJLC0O5L4+/2HUtvKIFdO8QNUn9GvfTQsc6TEFflC5z3xVyuu1MNsuhNRhUgQdncJu80jAw1CHpJPzyjAeYC/yRGPLEMwXxjH16uNZF9pR2Y7F3ClpRp4ZZXQHBl3NQA7LaGYQSLaxCDA+qN9TCpptPC1irO+FasyS8bUOT46cxJ4Pk22Gz4CtWXXhYx9yT33cqGLlp2I14sXGrIwCnXaDLvxg01/kVivUd4AwcMTZFai0oOOgvkR6Bjafgs0oz1xyqL4gHoP2PKkTuINnRL+OxxGY4YXikvXPW2nxFSGTQB0FT12DdGgwmJo+porFbePJNB2VsJFUEz40ZR5ATmCezj2QDpWVfW4ZGsuhgqS9T3mQR8eOLXJdhpWfD3n4Pq9Uy4jH+BIBh1n43E/xiQRYhiYShXyld60WICw2sQg8chw1TYwV6wGbEV9BTYojwH1MPDa06Uqij/dDt3AR/fmH9nkUcoW1SQNHkua9N1u2sk4iuBHWzsMJNIHAMYYqJm23xh7mZYfFXSD7eQfmeBeZITwpFV1hnUHqwuS6Xv6dcQwrUOfhyG/Lyb3sNMVroMPDVyDp9jBaiNYRUT0vbx20CZqn4Sf3nVokcK5hrmhMJmz+6f7aFtTLIlfwCd1B7ibQXE+L0+N7n+MqvvvKhZjxBi2B9EDfmH0r92Cn8OVN2akzEvyxOrCN6Ghma/PPUqy+RZFJswq0P1hMyvqfHwCFmjyjqi7f21tMHfkPYo7C4AAgsOJdAiJZxfdKul5y7AgiCsr5Q8q7NYodYS/IVNsQN9GIfbJTn3IjULVDp6qFR1wytiR5d6yHzB80RDizlltoYQhayulZVJ/dQ3eVyqM7uCZOjQnokcpbpaxcIkPdP/Rhjt5A5g2kqSKlCiM8QP5iT9SiityOrC3MENCVMnTxolp15IWy3njjX2dhk1M1SkpYENRs6Pfg2ateBwKvAvQS8DgGl+MQdTP24KKK4Srz6rbX5+1nHt+kvytw7c41Ca/MCST3ViU5BW4eJsXSBcZ+mVzLQNLEEO8IPatamaFL83jyT/PI0XgjYRx+506KEb4Nv+RSqno7BLxoAvtCpf+TEmkYBp+/9GDblmHZX4LAAn/URyTy6+251TEssr2n2aSjTNI13zxQhXsHmFDnfZ4UuSmdqw+vISY3hq1Kz8xW0lHbf1hCurn6SvcHg5gOWo0hUkB7aLojqPTnI+q88seK090ljc3RXM9mRntHEtG6V5JOArNIurjtM9TcZCp/+TfwN7xlz5GvVmq3u+5NvjOP5y4OYemEZV3VNgzH55vh/hE0bTGsCjh67YTdeLYYqG4heKjZQvdTLGr3L/TYwOq1NfJyy+gGkO6Evs/CJB6hHlXMDmThVDfb2ZurcdE9TDCbXjEg/5MzYiKf+BvClx9PbRqDpN4ZQD8gWLCdPfrNyQiaScymXhFIjPYJtkP49io+TetbTzWgaf46mS3tnRapfBXsRPD/IEH+o8RrDUH8IYScR9r9HkoYrGvw0nomC56Jh+HrS6pFuVn16gFkVEXEfTnkpVU9jM6ofuXg9YXGVlAFVpVgHDHitBztYqlou7qnEGZCQRCrAa4ZmKTKWArATydHYiWhL9ddj/GynWJCIEXBT6biQRSKrOVCFQ/YBnH8r45bxSTWBGQtLTMUT7sIg/qZeyIba9eshBxafjKjbAR9tlvdkHxCiduV3Cc1FDlNyqNg5kd/lYJ6i5b/l+5A+d9GYNLPPWqwsNIVYIs0b/NyQdKDXgKWIecDkpYVIKYn9+ReLaYwXkRolGhELSy/91Y5ygU/5RtvpgrNdNQsHKviDjP7vfxvDKZY3EdyiZmwm8d3iT2gvoao2WZ4OB1JxMQHnhS/jWkFif4ULksIPH1w98DYsd6Mch+wgutbktJLyPiSfUV/ZJiX9XHDqXwBAL5qeJr72HXyouUbk6ZRNup9KNSA3Lou7PAepED+pWxMzXFwAkdrvhaLWCgJD1BSkRqMykEt7YDgbeIx7kzxpuvlSbNQp4gYkHnQdUo9svsg4h4bk6A/3TElmCvqmC8WejKcwwRvR0APNKDRpK3nbgH8panOPT1QtK6IrwYYmLzN90q+61XWHQS7GD9ciFD40IlZ4XlP5E68o+EKZKn8+R1lFc4XhknnjXH8nqsVVvXNW8ymYQSRY7n7KnU66yZ4sgAQYFKwUx9t1tdzWUWA++k3ezXdb/zMrKEwocpHVGlfCyT1Qk2hjnx2+x+l8p5DBe5aKd1HSZRt8zYXI4Paw259dCrkRqqRRbWLheDB35JHJLnLK0EZiBkiU3fHjOv4QUE25O79dWDdAXABOktJOUII9gbYcYbW6+u85DEh8CdmTashykRqo3i0liccAWHYQZasDimqfDgBkNMzmpqs9pd8mXe8P1I2JXFqmtNFFhDE52RNkt9p7CMaUY75j6/mu+L9ADAEmYlpRDNjOkRR465XWhGMPXNpO3Qw3y6unpZPwQYjlqMuWfTEcgoq+W6lTvo9ZAgNM9kvqVefKiJ9Z33fg0Ov881hBh9ZImwjLbFmmUkyx0/xnf9e9SuDt3yNWc9swwkHz2sRFhprfh0AKlK6EFzXwMuE9Q5H/BqIV3/I3Xdx0a5L9lVjmGJNdVz4G7JVo2MQcA1XwBuHnVkKQoc+4c4lQB24tA==
---

